### ISSUE TITLE
The "Measuring the temperature" Example 

### ISSUE THREAD

**Issue by AlanGitMan** [particle-iot-archived/docs-old#252]
The circuit diagram shows the temp sensor connected to A0, the associated code is attempting to read the temperature from pin A7... seems wrong?

Best regards
Alan T

**Comment by kennethlimcp** [comment]
@AlanGitMan thanks! Seems more like a illustration issue.

http://docs.spark.io/assets/images/annotated-example3.jpg is incorrect showing connection to A0 while the latter shows A7 which tallies with the code.

@technobly can you make a new fritzing diagram since you probably have it setup already?

**Comment by kennethlimcp** [comment]
@AlanGitMan, thanks once again i have updated the schematic! ;)

**Comment by technobly** [comment]
Should have changed the code instead of the diagram, the old diagram with A0 has two issues: 1) the ground for the capacitor is routed poorly, and 2) the TMP36 is better suited if you move it as far away from the Spark Core as possible because the Core heats up the breadboard and causes a significant temperature error in the TMP36.  If possible, locate the TMP36 on a separate breadboard or at the end of a 3-wire cable.

**Comment by technobly** [comment]
Ahh, I see what the problem was now.  We changed everything long ago from A0 to A7 and the code and fritzing diagram were correct.  The bad part was we left the old actual photo of the A0 wiring with no capacitor.  I put the fritzing image back and removed the A0 photo in these last two commits:
https://github.com/spark/docs/commit/d70a3bfbfff878829ff9cf4022916efc73446173
https://github.com/spark/docs/commit/2f895ed21774e2853a99d71fdcfd877dd20c7337
