### ISSUE TITLE
Time.zone() doesn't explain how to use it

### ISSUE THREAD

**Issue by harrisonhjones** [particle-iot-archived/docs-old#257]
The Time.zone() function explains that it sets the current timezone offset. Nowhere in the documentation (that I can find) does it explain how to use this modified, timezone-aware, version of time. Time.now() only ever returns true GMT-0 time and CalendarTime isn't exposed in the docs. 

Suggestions:
Either 1. alter the now() code so it uses the zone offset or 2. alter the docs to explain how to get local/timezone time.

**Comment by pkourany** [comment]
@harrisonhjones, I agree that there is an issue.  Using any of the time methods line now(), hour(), minute(), etc. returns GMT-0 based time.  However, using hour(time_t t), day(time_t t) where t is a give (Unitx) time returns a timezone adjusted value.  So hour(time.now()) would return a time zone adjusted hour.  If anything, the document should clarify these functional differences.

**Comment by kennethlimcp** [comment]
I'll write up a test code and see what's the current behavior.

**Comment by kennethlimcp** [comment]
@pkourany, in my test i found the following:

1.) Calling the year(), hour(), minute(), second() etc etc all returns value from the adjusted time.

2.) `now()` is the only function returning the GMT-0 based time and aligns with the Arduino Time library implementation

3.) The docs seems ok for me except that there is currently no way to retrieve a GMT adjusted unix time stamp since `now()` returns the GMT-0 unix timestamp.

The code i wrote is here: https://gist.github.com/kennethlimcp/976f262fd7a2300c88b0

@harrisonhjones, back to the issue you filed, the behavior of `now()` is correct as per the Arduino Time library but not 100% confident if they are returning adjusted-time instead. See: https://github.com/PaulStoffregen/Time/blob/master/Time.cpp#L250

Maybe i can open an issue to ask a question
