### ISSUE TITLE
Human Readable Device Names

### ISSUE THREAD

**Issue by towynlin** [particle-iot-archived/docs-old#3]
Devices will have long, ugly IDs, but when someone is just getting started with their first couple Cores, they should be able to give them names and refer to the names in API calls.

The full implementation of this is not required until we ship Cores this Summer.

**Comment by joegoggins** [comment]
This is implemented in the backend, thus a request like:

```
curl 'https://api.spark.io/v1/devices/beef68064989495329092587?access_token=1234560eccaaa9a3359f81f75742bda54a7214d3b'
```

where `beef68064989495329092587` is named `trusty_core`, is equivalent to:

```
curl 'https://api.spark.io/v1/devices/trusty_core?access_token=1234560eccaaa9a3359f81f75742bda54a7214d3b'
```

I propose we change the docs to read "DEVICE_ID_OR_NAME" anywhere "DEVICE_ID" occurs.
Additionally, for examples we should use friendly names instead of ids. For the sake of consistency, let's use `trusty_core`.

@towynlin sound good to you?

**Comment by towynlin** [comment]
I definitely like the change from example IDs to `trusty_core`.

I approve generally of the principle of `DEVICE_ID_OR_NAME` however, I wonder whether that will look ugly by going over our limited horizontal space and cause horizontal scrolling in a lot of places in the existing docs.  Perhaps try it (with reasonably small browser window width, as opposed to entire enormous monitor width) and see whether ugliness happens.  Use your judgement.  If ugly, I'd rather leave it as `DEVICE_ID` or change to `DEVICE_NAME`.

**Comment by towynlin** [comment]
I would call 80% to 90% of laptop screen a reasonable width for browser windows.
